insert into public.sources (
  code,
  name,
  homepage_url,
  robots_url,
  rank_overall,
  crawl_priority,
  is_active,
  crawl_interval_minutes,
  crawl_policy,
  crawler_config,
  notes
) values
(
  'revu',
  '레뷰 REVU',
  'https://www.revu.net/',
  'https://www.revu.net/robots.txt',
  1,
  null,
  false,
  360,
  '{"status":"needs_dynamic_analysis","reason":"Angular app; campaign cards are not present in initial HTML. Campaign paths are not explicitly blocked by robots, but parser/API analysis is needed before activation."}'::jsonb,
  '{"parser":"revu_dynamic_tbd","detail_fetch":false}'::jsonb,
  '인지도 상위 후보. MVP 자동 수집은 비활성.'
),
(
  'reviewnote',
  '리뷰노트',
  'https://www.reviewnote.co.kr/',
  'https://www.reviewnote.co.kr/robots.txt',
  2,
  10,
  true,
  120,
  '{"status":"homepage_only","reason":"robots.txt disallows /campaigns/. Crawl only campaign snippets already rendered on the allowed homepage; do not fetch campaign detail/list pages."}'::jsonb,
  '{"parser":"reviewnote_homepage","target_url":"https://www.reviewnote.co.kr/","allowed_link_patterns":["/campaigns/"],"detail_fetch":false}'::jsonb,
  '상세/목록 경로 자동 접근 금지. 홈페이지 노출 카드만 샘플 수집.'
),
(
  'dinnerqueen',
  '디너의여왕',
  'https://dinnerqueen.net/',
  'https://dinnerqueen.net/robots.txt',
  3,
  null,
  false,
  180,
  '{"status":"temporarily_disabled","reason":"robots.txt allows general crawling, but current Python TLS/body fetch was unstable in this environment. Re-test from GitHub Actions before activation."}'::jsonb,
  '{"parser":"dinnerqueen_tbd","detail_fetch":false}'::jsonb,
  '정책상 후보는 좋지만 현재 환경에서 본문 수집이 불안정.'
),
(
  'gangnammatzip',
  '강남맛집 체험단',
  'https://xn--939au0g4vj8sq.net/',
  'https://xn--939au0g4vj8sq.net/robots.txt',
  4,
  20,
  true,
  120,
  '{"status":"homepage_only","reason":"robots.txt allows root and many public paths but blocks several admin/review paths. Start with homepage snippets only."}'::jsonb,
  '{"parser":"gangnammatzip_homepage","target_url":"https://xn--939au0g4vj8sq.net/","allowed_link_patterns":["/cp/?id="],"detail_fetch":false}'::jsonb,
  '홈페이지 인기/마감임박 카드 수집 가능.'
),
(
  'reviewplace',
  '리뷰플레이스',
  'https://www.reviewplace.co.kr/',
  'https://www.reviewplace.co.kr/robots.txt',
  5,
  40,
  true,
  120,
  '{"status":"homepage_only","reason":"robots.txt disallows /pr and several detail/list paths. Crawl only campaign snippets already rendered on the allowed homepage."}'::jsonb,
  '{"parser":"reviewplace_homepage","target_url":"https://www.reviewplace.co.kr/","allowed_link_patterns":["/pr/?id="],"detail_fetch":false}'::jsonb,
  '홈페이지 실시간 인기캠페인 카드만 수집.'
),
(
  'ringble',
  '링블',
  'https://www.ringble.co.kr/',
  'https://www.ringble.co.kr/robots.txt',
  6,
  30,
  true,
  120,
  '{"status":"homepage_only","reason":"robots.txt disallows detail.php. Crawl only detail links and snippets already rendered on the allowed homepage; do not fetch details."}'::jsonb,
  '{"parser":"ringble_homepage","target_url":"https://www.ringble.co.kr/","allowed_link_patterns":["detail.php?number="],"detail_fetch":false}'::jsonb,
  '제품/방문/인스타/유튜브 카테고리 노출. 상세 fetch 금지.'
),
(
  'tble',
  '티블',
  'https://tble.kr/',
  'https://www.tble.kr/robots.txt',
  7,
  50,
  true,
  120,
  '{"status":"homepage_only","reason":"robots.txt disallows category and view query paths. Crawl only campaign snippets already rendered on the allowed homepage."}'::jsonb,
  '{"parser":"tble_homepage","target_url":"https://tble.kr/","allowed_link_patterns":["view.php?cp_id="],"detail_fetch":false}'::jsonb,
  '홈페이지 인기 캠페인 카드 수집 가능.'
)
on conflict (code) do update set
  name = excluded.name,
  homepage_url = excluded.homepage_url,
  robots_url = excluded.robots_url,
  rank_overall = excluded.rank_overall,
  crawl_priority = excluded.crawl_priority,
  is_active = excluded.is_active,
  crawl_interval_minutes = excluded.crawl_interval_minutes,
  crawl_policy = excluded.crawl_policy,
  crawler_config = excluded.crawler_config,
  notes = excluded.notes;
