insert into public.sources (
  code,
  name,
  homepage_url,
  robots_url,
  rank_overall,
  crawl_priority,
  is_active,
  crawl_interval_minutes,
  crawl_policy,
  crawler_config,
  notes
) values
(
  'revu',
  '레뷰 REVU',
  'https://www.revu.net/',
  'https://www.revu.net/robots.txt',
  1,
  10,
  false,
  360,
  '{"source_mode":"candidate","status":"candidate","reason":"High-priority source, but campaign cards are not present in initial homepage HTML. Needs dynamic rendering or official integration analysis before activation.","detail_fetch":false}'::jsonb,
  '{"parser":"revu_dynamic_tbd","target_url":"https://www.revu.net/","allowed_link_patterns":[],"detail_fetch":false,"source_mode":"candidate"}'::jsonb,
  '인지도 최상위 후보. 초기 HTML에 캠페인 카드가 거의 없어 비활성.'
),
(
  'reviewnote',
  '리뷰노트',
  'https://www.reviewnote.co.kr/',
  'https://www.reviewnote.co.kr/robots.txt',
  2,
  20,
  true,
  120,
  '{"source_mode":"summary_only","status":"crawlable","reason":"robots.txt disallows /campaigns/. Fetch only the allowed homepage and store snippets already rendered there.","detail_fetch":false}'::jsonb,
  '{"parser":"reviewnote_homepage","target_url":"https://www.reviewnote.co.kr/","allowed_link_patterns":["/campaigns/"],"detail_fetch":false,"source_mode":"summary_only"}'::jsonb,
  '상세/목록 경로 자동 접근 금지. 홈페이지 노출 카드만 수집.'
),
(
  'seoulouba',
  '서울오빠',
  'https://www.seoulouba.co.kr/',
  'https://www.seoulouba.co.kr/robots.txt',
  3,
  30,
  true,
  120,
  '{"source_mode":"summary_only","status":"crawlable","reason":"robots.txt allows only the homepage. Fetch the homepage only and store campaign links/snippets already rendered there.","detail_fetch":false}'::jsonb,
  '{"parser":"seoulouba_homepage","target_url":"https://www.seoulouba.co.kr/","allowed_link_patterns":["campaign/?c="],"detail_fetch":false,"source_mode":"summary_only"}'::jsonb,
  '홈 요약 수집. 상세/목록 자동 접근 금지.'
),
(
  'dinnerqueen',
  '디너의여왕',
  'https://dinnerqueen.net/taste',
  'https://dinnerqueen.net/robots.txt',
  4,
  40,
  true,
  120,
  '{"source_mode":"summary_only","status":"crawlable","reason":"Fetch the allowed /taste listing page only. Do not fetch query-filtered pages or campaign detail pages.","detail_fetch":false}'::jsonb,
  '{"parser":"dinnerqueen_homepage","target_url":"https://dinnerqueen.net/taste","allowed_link_patterns":["/taste/"],"detail_fetch":false,"source_mode":"summary_only"}'::jsonb,
  '맛집/푸드 대형 후보. /taste 목록 요약만 수집.'
),
(
  'modublog',
  '모블',
  'https://www.modublog.co.kr/',
  'https://www.modublog.co.kr/robots.txt',
  5,
  50,
  true,
  120,
  '{"source_mode":"summary_only","status":"crawlable","reason":"robots.txt allows the homepage. Fetch the homepage only and store product campaign snippets already rendered there.","detail_fetch":false}'::jsonb,
  '{"parser":"modublog_homepage","target_url":"https://www.modublog.co.kr/","allowed_link_patterns":["/product/"],"detail_fetch":false,"source_mode":"summary_only"}'::jsonb,
  '홈 요약 수집. 제품 상세 자동 접근 금지.'
),
(
  'gangnammatzip',
  '강남맛집 체험단',
  'https://xn--939au0g4vj8sq.net/',
  'https://xn--939au0g4vj8sq.net/robots.txt',
  6,
  60,
  true,
  120,
  '{"source_mode":"summary_only","status":"crawlable","reason":"Fetch homepage snippets only.","detail_fetch":false}'::jsonb,
  '{"parser":"gangnammatzip_homepage","target_url":"https://xn--939au0g4vj8sq.net/","allowed_link_patterns":["/cp/?id="],"detail_fetch":false,"source_mode":"summary_only"}'::jsonb,
  '홈페이지 인기/마감임박 카드 수집.'
),
(
  'ringble',
  '링블',
  'https://www.ringble.co.kr/',
  'https://www.ringble.co.kr/robots.txt',
  7,
  70,
  true,
  120,
  '{"source_mode":"summary_only","status":"crawlable","reason":"robots.txt disallows detail.php. Fetch only the allowed homepage.","detail_fetch":false}'::jsonb,
  '{"parser":"ringble_homepage","target_url":"https://www.ringble.co.kr/","allowed_link_patterns":["detail.php?number="],"detail_fetch":false,"source_mode":"summary_only"}'::jsonb,
  '홈페이지 카드만 수집. 상세 fetch 금지.'
),
(
  'reviewplace',
  '리뷰플레이스',
  'https://www.reviewplace.co.kr/',
  'https://www.reviewplace.co.kr/robots.txt',
  8,
  80,
  true,
  120,
  '{"source_mode":"summary_only","status":"crawlable","reason":"robots.txt disallows /pr. Fetch only the allowed homepage.","detail_fetch":false}'::jsonb,
  '{"parser":"reviewplace_homepage","target_url":"https://www.reviewplace.co.kr/","allowed_link_patterns":["/pr/?id="],"detail_fetch":false,"source_mode":"summary_only"}'::jsonb,
  '홈페이지 실시간 인기캠페인 카드만 수집.'
),
(
  'tble',
  '티블',
  'https://tble.kr/',
  'https://tble.kr/robots.txt',
  9,
  90,
  true,
  120,
  '{"source_mode":"summary_only","status":"crawlable","reason":"robots.txt disallows view/category paths. Fetch only the allowed homepage.","detail_fetch":false}'::jsonb,
  '{"parser":"tble_homepage","target_url":"https://tble.kr/","allowed_link_patterns":["view.php?cp_id="],"detail_fetch":false,"source_mode":"summary_only"}'::jsonb,
  '홈페이지 인기 캠페인 카드 수집 가능.'
),
(
  'reviewshare',
  '리뷰쉐어',
  'https://reviewshare.io/',
  'https://reviewshare.io/robots.txt',
  10,
  100,
  false,
  360,
  '{"source_mode":"blocked","status":"blocked","reason":"Campaign project pages are disallowed by robots.txt and the homepage has no usable campaign snippets.","detail_fetch":false}'::jsonb,
  '{"parser":"reviewshare_project_blocked","target_url":"https://reviewshare.io/","allowed_link_patterns":[],"detail_fetch":false,"source_mode":"blocked"}'::jsonb,
  '프로젝트 경로 robots 차단. 제휴/API 후보.'
)
on conflict (code) do update set
  name = excluded.name,
  homepage_url = excluded.homepage_url,
  robots_url = excluded.robots_url,
  rank_overall = excluded.rank_overall,
  crawl_priority = excluded.crawl_priority,
  is_active = excluded.is_active,
  crawl_interval_minutes = excluded.crawl_interval_minutes,
  crawl_policy = excluded.crawl_policy,
  crawler_config = excluded.crawler_config,
  notes = excluded.notes;
